# Generated by Django 4.2.23 on 2025-10-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result_base_editor_list',
            fields=[
                ('task_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pam_type', models.CharField(max_length=30)),
                ('name_db', models.CharField(max_length=255)),
                ('input_sequence', models.TextField()),
                ('sequence_position', models.TextField(default='')),
                ('sgRNA_module', models.CharField(max_length=20)),
                ('spacer_length', models.PositiveSmallIntegerField()),
                ('base_editor_type', models.CharField(choices=[('ABE', 'ABE (A to G)'), ('CBE', 'CBE (C to T)'), ('GBE', 'GBE (C to G)'), ('ABE+CBE', 'ABE+CBE')], max_length=10)),
                ('base_editing_window', models.CharField(max_length=10)),
                ('sgRNA_with_JBrowse_json', models.JSONField(default=dict)),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('log', models.TextField(default='')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
