# Generated by Django 4.2.23 on 2025-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result_cas12a_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('input_sequence', models.TextField()),
                ('pam_type', models.CharField(max_length=50)),
                ('spacer_length', models.IntegerField()),
                ('sgRNA_module', models.CharField(max_length=50)),
                ('name_db', models.CharField(max_length=200)),
                ('task_status', models.CharField(choices=[('analysis', 'Analysis'), ('success', 'Success'), ('failure', 'Failure'), ('partial_success', 'Partial Success')], default='analysis', max_length=50)),
                ('sgRNA_json', models.JSONField(blank=True, null=True)),
                ('sgRNA_with_JBrowse_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='result_cas12b_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('input_sequence', models.TextField()),
                ('pam_type', models.CharField(max_length=50)),
                ('spacer_length', models.IntegerField()),
                ('sgRNA_module', models.CharField(max_length=50)),
                ('name_db', models.CharField(max_length=200)),
                ('task_status', models.CharField(choices=[('analysis', 'Analysis'), ('success', 'Success'), ('failure', 'Failure'), ('partial_success', 'Partial Success')], default='analysis', max_length=50)),
                ('sgRNA_json', models.JSONField(blank=True, null=True)),
                ('sgRNA_with_JBrowse_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
