# Generated by Django 4.2.23 on 2025-08-26 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditAnalysisFiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_md5', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'edit_analysis_files',
            },
        ),
        migrations.CreateModel(
            name='EditAnalysisTasks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fq_files_md5', models.CharField(max_length=64)),
                ('target_file_md5', models.CharField(max_length=64)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('analysis', 'Analysis'), ('success', 'Success'), ('failure', 'Failure')], default='analysis', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('time_of_completion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edit_analysis_tasks',
                'indexes': [models.Index(fields=['fq_files_md5', 'target_file_md5', 'start', 'end'], name='edit_analys_fq_file_e1e855_idx')],
            },
        ),
    ]
