# Generated by Django 4.2.23 on 2025-08-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editanalysistasks',
            name='status',
            field=models.CharField(choices=[('analysis', 'Analysis'), ('success', 'Success'), ('failure', 'Failure'), ('partial_success', 'Partial Success')], default='analysis', max_length=20),
        ),
    ]
