# Generated by Django 4.2.23 on 2025-10-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result_crispra_list',
            fields=[
                ('task_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pam_type', models.CharField(max_length=30)),
                ('name_db', models.CharField(max_length=255)),
                ('input_sequence', models.TextField()),
                ('sequence_position', models.TextField(default='')),
                ('sgRNA_module', models.CharField(max_length=20)),
                ('spacer_length', models.PositiveSmallIntegerField()),
                ('upstream_sequence_length', models.PositiveIntegerField(default=2000)),
                ('sgRNA_with_JBrowse_json', models.JSONField(default=dict)),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('log', models.TextField(default='')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
